name: Update episode list

on:
  schedule:
    # Runs daily at 00:00 UTC
    - cron: '0 0 * * *'
  # Allows manual triggering of the workflow from the GitHub UI
  workflow_dispatch:

jobs:
  update-and-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: "pip"
      - name: Install Python dependencies
        run: pip install -r requirements.txt
      - name: Run update script
        run: python drolet_bible.py
        env: 
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Add latest episodes"
